DROP TABLE IF EXISTS `Reports`;
CREATE TABLE `Reports` (
  `Date` date,
  `Name` char(40) default '',
  `Street` char(25)   default '',
  `Zip` int(5) default NULL,
  `CrimeType` char(17) ,
  `Area` int(5) ,
  `TimePeriod` char(10) default NULL,
  `PropertyDescription` char(70) default NULL,
  `RecoveredValue` int(10) ,
  `LostStolenDamagedValue` int(10)  ,
  `Assignment` char(30)   default '',
  `Status` char(15)   default '',
  `FelonyMisd` char(14) default '',
  `GangRel` char(5) default '',
  `ArrestsMade` int(4)  ,
  `ComplaintNum` int(10) AUTO_INCREMENT NOT NULL ,
  `DetecAssist1` char(30)   default '',
  `DetecAssist2` char(30)   default '',
  `DetecAssist3` char(30)   default '',
  `DetecAssist4` char(30)   default '',
  `DetecAssist5` char(30)   default '',
  `PrintDna` char(12)   default '',
  `BusinessName` char(30)   default '',
  `Remarks` char(200)   default '',
  PRIMARY KEY  (`ComplaintNum`),
  FOREIGN KEY(`Zip`) references zipcode(Zip)
);
