DROP TABLE IF EXISTS `ZipCode`;
CREATE TABLE `ZipCode` (
  `City` varchar(40) not null,
  `State` char(10) not null,
  `Zip` int(5),
  `Township` varchar(40) not null,
  PRIMARY KEY  (`Zip`)
);


INSERT INTO zipcode VALUES('Algonac','MI','48001','Saint Clair');
INSERT INTO zipcode VALUES('Allenton','MI','48002','Saint Clair');
INSERT INTO zipcode VALUES('Almont','MI','48003','Lapeer');
INSERT INTO zipcode VALUES('Anchorville','MI','48004','Saint Clair');
INSERT INTO zipcode VALUES('Armada','MI','48005','Macomb');
INSERT INTO zipcode VALUES('Avoca','MI','48006','Saint Clair');
INSERT INTO zipcode VALUES('Troy','MI','48007','Oakland');
INSERT INTO zipcode VALUES('Birmingham','MI','48009','Oakland');
INSERT INTO zipcode VALUES('Birmingham','MI','48012','Oakland');
INSERT INTO zipcode VALUES('Capac','MI','48014','Saint Clair');
INSERT INTO zipcode VALUES('Center Line','MI','48015','Macomb');
INSERT INTO zipcode VALUES('Clawson','MI','48017','Oakland');
INSERT INTO zipcode VALUES('Eastpointe','MI','48021','Macomb');
INSERT INTO zipcode VALUES('Emmett','MI','48022','Saint Clair');
INSERT INTO zipcode VALUES('Fair Haven','MI','48023','Saint Clair');
INSERT INTO zipcode VALUES('Franklin','MI','48025','Oakland');
INSERT INTO zipcode VALUES('Fraser','MI','48026','Macomb');
INSERT INTO zipcode VALUES('Goodells','MI','48027','Saint Clair');
INSERT INTO zipcode VALUES('Harsens Island','MI','48028','Saint Clair');
INSERT INTO zipcode VALUES('Hazel Park','MI','48030','Oakland');
INSERT INTO zipcode VALUES('Jeddo','MI','48032','Saint Clair');
INSERT INTO zipcode VALUES('Southfield','MI','48034','Oakland');
INSERT INTO zipcode VALUES('Clinton Township','MI','48035','Macomb');
INSERT INTO zipcode VALUES('Clinton Township','MI','48036','Macomb');
INSERT INTO zipcode VALUES('Southfield','MI','48037','Oakland');
INSERT INTO zipcode VALUES('Clinton Township','MI','48038','Macomb');
INSERT INTO zipcode VALUES('Marine City','MI','48039','Saint Clair');
INSERT INTO zipcode VALUES('Marysville','MI','48040','Saint Clair');
INSERT INTO zipcode VALUES('Memphis','MI','48041','Saint Clair');
INSERT INTO zipcode VALUES('Macomb','MI','48042','Macomb');
INSERT INTO zipcode VALUES('Mount Clemens','MI','48043','Macomb');
INSERT INTO zipcode VALUES('Macomb','MI','48044','Macomb');
INSERT INTO zipcode VALUES('Harrison Township','MI','48045','Macomb');
INSERT INTO zipcode VALUES('Mount Clemens','MI','48046','Macomb');
INSERT INTO zipcode VALUES('New Baltimore','MI','48047','Macomb');
INSERT INTO zipcode VALUES('New Haven','MI','48048','Macomb');
INSERT INTO zipcode VALUES('North Street','MI','48049','Saint Clair');
INSERT INTO zipcode VALUES('New Haven','MI','48050','Macomb');
INSERT INTO zipcode VALUES('New Baltimore','MI','48051','Macomb');
INSERT INTO zipcode VALUES('East China','MI','48054','Saint Clair');
INSERT INTO zipcode VALUES('Fort Gratiot','MI','48059','Saint Clair');
INSERT INTO zipcode VALUES('Port Huron','MI','48060','Saint Clair');
INSERT INTO zipcode VALUES('Port Huron','MI','48061','Saint Clair');
INSERT INTO zipcode VALUES('Richmond','MI','48062','Macomb');
INSERT INTO zipcode VALUES('Columbus','MI','48063','Saint Clair');
INSERT INTO zipcode VALUES('Casco','MI','48064','Saint Clair');
INSERT INTO zipcode VALUES('Romeo','MI','48065','Macomb');
INSERT INTO zipcode VALUES('Roseville','MI','48066','Macomb');
INSERT INTO zipcode VALUES('Royal Oak','MI','48067','Oakland');
INSERT INTO zipcode VALUES('Royal Oak','MI','48068','Oakland');
INSERT INTO zipcode VALUES('Pleasant Ridge','MI','48069','Oakland');
INSERT INTO zipcode VALUES('Huntington Woods','MI','48070','Oakland');
INSERT INTO zipcode VALUES('Madison Heights','MI','48071','Oakland');
INSERT INTO zipcode VALUES('Berkley','MI','48072','Oakland');
INSERT INTO zipcode VALUES('Royal Oak','MI','48073','Oakland');
INSERT INTO zipcode VALUES('Smiths Creek','MI','48074','Saint Clair');
INSERT INTO zipcode VALUES('Southfield','MI','48075','Oakland');
INSERT INTO zipcode VALUES('Southfield','MI','48076','Oakland');
INSERT INTO zipcode VALUES('Saint Clair','MI','48079','Saint Clair');
INSERT INTO zipcode VALUES('Saint Clair','MI','48080','Michigan Macomb');
INSERT INTO zipcode VALUES('Saint Clair','MI','48081','Michigan Macomb');
INSERT INTO zipcode VALUES('Saint Clair','MI','48082','Michigan Macomb');
INSERT INTO zipcode VALUES('Troy','MI','48083','Oakland');
INSERT INTO zipcode VALUES('Troy','MI','48084','Oakland');
INSERT INTO zipcode VALUES('Southfield','MI','48086','Oakland');
INSERT INTO zipcode VALUES('Warren','MI','48089','Macomb');
INSERT INTO zipcode VALUES('Warren','MI','48090','Macomb');
INSERT INTO zipcode VALUES('Warren','MI','48091','Macomb');
INSERT INTO zipcode VALUES('Warren','MI','48092','Macomb');
INSERT INTO zipcode VALUES('Warren','MI','48093','Macomb');
INSERT INTO zipcode VALUES('Washington','MI','48094','Macomb');
INSERT INTO zipcode VALUES('Washington','MI','48095','Macomb');
INSERT INTO zipcode VALUES('Ray','MI','48096','Macomb');
INSERT INTO zipcode VALUES('Yale','MI','48097','Saint Clair');
INSERT INTO zipcode VALUES('Troy','MI','48098','Oakland');
INSERT INTO zipcode VALUES('Troy','MI','48099','Oakland');
INSERT INTO zipcode VALUES('Allen Park','MI','48101','Wayne');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48103','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48104','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48105','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48106','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48107','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48108','Washtenaw');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48109','Washtenaw');
INSERT INTO zipcode VALUES('Azalia','MI','48110','Monroe');
INSERT INTO zipcode VALUES('Belleville','MI','48111','Wayne');
INSERT INTO zipcode VALUES('Belleville','MI','48112','Wayne');
INSERT INTO zipcode VALUES('Ann Arbor','MI','48113','Washtenaw');
INSERT INTO zipcode VALUES('Brighton','MI','48114','Livingston');
INSERT INTO zipcode VALUES('Bridgewater','MI','48115','Washtenaw');
INSERT INTO zipcode VALUES('Brighton','MI','48116','Livingston');
INSERT INTO zipcode VALUES('Carleton','MI','48117','Monroe');
INSERT INTO zipcode VALUES('Chelsea','MI','48118','Washtenaw');
INSERT INTO zipcode VALUES('Dearborn','MI','48120','Wayne');
INSERT INTO zipcode VALUES('Dearborn','MI','48121','Wayne');
INSERT INTO zipcode VALUES('Melvindale','MI','48122','Wayne');
INSERT INTO zipcode VALUES('Dearborn','MI','48123','Wayne');
INSERT INTO zipcode VALUES('Dearborn','MI','48124','Wayne');
INSERT INTO zipcode VALUES('Dearborn Heights','MI','48125','Wayne');
INSERT INTO zipcode VALUES('Dearborn','MI','48126','Wayne');
INSERT INTO zipcode VALUES('Dearborn Heights','MI','48127','Wayne');
INSERT INTO zipcode VALUES('Dearborn','MI','48128','Wayne');
INSERT INTO zipcode VALUES('Dexter','MI','48130','Washtenaw');
INSERT INTO zipcode VALUES('Dundee','MI','48131','Monroe');
INSERT INTO zipcode VALUES('Erie','MI','48133','Monroe');
INSERT INTO zipcode VALUES('Flat Rock','MI','48134','Wayne');
INSERT INTO zipcode VALUES('Garden City','MI','48135','Wayne');
INSERT INTO zipcode VALUES('Garden City','MI','48136','Wayne');
INSERT INTO zipcode VALUES('Gregory','MI','48137','Livingston');
INSERT INTO zipcode VALUES('Grosse Ile','MI','48138','Wayne');
INSERT INTO zipcode VALUES('Hamburg','MI','48139','Livingston');
INSERT INTO zipcode VALUES('Ida','MI','48140','Monroe');
INSERT INTO zipcode VALUES('Inkster','MI','48141','Wayne');
INSERT INTO zipcode VALUES('Lakeland','MI','48143','Livingston');
INSERT INTO zipcode VALUES('Lambertville','MI','48144','Monroe');
INSERT INTO zipcode VALUES('La Salle','MI','48145','Monroe');
INSERT INTO zipcode VALUES('Lincoln Park','MI','48146','Wayne');
INSERT INTO zipcode VALUES('Livonia','MI','48150','Wayne');
INSERT INTO zipcode VALUES('Livonia','MI','48151','Wayne');
INSERT INTO zipcode VALUES('Livonia','MI','48152','Wayne');
INSERT INTO zipcode VALUES('Livonia','MI','48153','Wayne');
INSERT INTO zipcode VALUES('Livonia','MI','48154','Wayne');
INSERT INTO zipcode VALUES('Luna Pier','MI','48157','Monroe');
INSERT INTO zipcode VALUES('Manchester','MI','48158','Washtenaw');
INSERT INTO zipcode VALUES('Maybee','MI','48159','Monroe');
INSERT INTO zipcode VALUES('Milan','MI','48160','Monroe');
INSERT INTO zipcode VALUES('Monroe','MI','48161','Monroe');
INSERT INTO zipcode VALUES('Monroe','MI','48162','Monroe');
INSERT INTO zipcode VALUES('New Boston','MI','48164','Wayne');
INSERT INTO zipcode VALUES('New Hudson','MI','48165','Oakland');
INSERT INTO zipcode VALUES('Newport','MI','48166','Monroe');
INSERT INTO zipcode VALUES('Northville','MI','48167','Wayne');
INSERT INTO zipcode VALUES('Pinckney','MI','48169','Livingston');
INSERT INTO zipcode VALUES('Plymouth','MI','48170','Wayne');
INSERT INTO zipcode VALUES('Rockwood','MI','48173','Wayne');
INSERT INTO zipcode VALUES('Romulus','MI','48174','Wayne');
INSERT INTO zipcode VALUES('Salem','MI','48175','Washtenaw');
INSERT INTO zipcode VALUES('Saline','MI','48176','Washtenaw');
INSERT INTO zipcode VALUES('Samaria','MI','48177','Monroe');
INSERT INTO zipcode VALUES('South Lyon','MI','48178','Oakland');
INSERT INTO zipcode VALUES('South Rockwood','MI','48179','Monroe');
INSERT INTO zipcode VALUES('Taylor','MI','48180','Wayne');
INSERT INTO zipcode VALUES('Temperance','MI','48182','Monroe');
INSERT INTO zipcode VALUES('Trenton','MI','48183','Wayne');
INSERT INTO zipcode VALUES('Wayne','MI','48184','Wayne');
INSERT INTO zipcode VALUES('Westland','MI','48185','Wayne');
INSERT INTO zipcode VALUES('Westland','MI','48186','Wayne');
INSERT INTO zipcode VALUES('Canton','MI','48187','Wayne');
INSERT INTO zipcode VALUES('Canton','MI','48188','Wayne');
INSERT INTO zipcode VALUES('Whitmore Lake','MI','48189','Washtenaw');
INSERT INTO zipcode VALUES('Whittaker','MI','48190','Washtenaw');
INSERT INTO zipcode VALUES('Willis','MI','48191','Washtenaw');
INSERT INTO zipcode VALUES('Wyandotte','MI','48192','Wayne');
INSERT INTO zipcode VALUES('Southgate','MI','48195','Wayne');
INSERT INTO zipcode VALUES('Ypsilanti','MI','48197','Washtenaw');
INSERT INTO zipcode VALUES('Ypsilanti','MI','48198','Washtenaw');
INSERT INTO zipcode VALUES('Detroit','MI','48201','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48202','Wayne');
INSERT INTO zipcode VALUES('Highland Park','MI','48203','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48204','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48205','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48206','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48207','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48208','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48209','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48210','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48211','Wayne');
INSERT INTO zipcode VALUES('Hamtramck','MI','48212','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48213','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48214','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48215','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48216','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48217','Wayne');
INSERT INTO zipcode VALUES('River Rouge','MI','48218','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48219','Wayne');
INSERT INTO zipcode VALUES('Ferndale','MI','48220','Oakland');
INSERT INTO zipcode VALUES('Detroit','MI','48221','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48222','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48223','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48224','Wayne');
INSERT INTO zipcode VALUES('Harper Woods','MI','48225','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48226','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48227','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48228','Wayne');
INSERT INTO zipcode VALUES('Ecorse','MI','48229','Wayne');
INSERT INTO zipcode VALUES('Grosse Pointe','MI','48230','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48231','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48232','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48233','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48234','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48235','Wayne');
INSERT INTO zipcode VALUES('Grosse Pointe','MI','48236','Wayne');
INSERT INTO zipcode VALUES('Oak Park','MI','48237','Oakland');
INSERT INTO zipcode VALUES('Detroit','MI','48238','Wayne');
INSERT INTO zipcode VALUES('Redford','MI','48239','Wayne');
INSERT INTO zipcode VALUES('Redford','MI','48240','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48242','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48243','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48244','Wayne');
INSERT INTO zipcode VALUES('-','MI','48254','-');
INSERT INTO zipcode VALUES('Detroit','MI','48255','Wayne');
INSERT INTO zipcode VALUES('-','MI','48258','-');
INSERT INTO zipcode VALUES('Detroit','MI','48260','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48264','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48265','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48266','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48267','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48268','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48269','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48272','Wayne');
INSERT INTO zipcode VALUES('-','MI','48274','-');
INSERT INTO zipcode VALUES('Detroit','MI','48275','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48277','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48278','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48279','Wayne');
INSERT INTO zipcode VALUES('Detroit','MI','48288','Wayne');
INSERT INTO zipcode VALUES('-','MI','48295','-');
INSERT INTO zipcode VALUES('-','MI','48297','-');
INSERT INTO zipcode VALUES('-','MI','48299','-');
INSERT INTO zipcode VALUES('Bloomfield Hills','MI','48301','Oakland');
INSERT INTO zipcode VALUES('Bloomfield Hills','MI','48302','Oakland');
INSERT INTO zipcode VALUES('Bloomfield Hills','MI','48303','Oakland');
INSERT INTO zipcode VALUES('Bloomfield Hills','MI','48304','Oakland');
INSERT INTO zipcode VALUES('Rochester','MI','48306','Oakland');
INSERT INTO zipcode VALUES('Rochester','MI','48307','Oakland');
INSERT INTO zipcode VALUES('Rochester','MI','48308','Oakland');
INSERT INTO zipcode VALUES('Rochester','MI','48309','Oakland');
INSERT INTO zipcode VALUES('Sterling Heights','MI','48310','Macomb');
INSERT INTO zipcode VALUES('Sterling Heights','MI','48311','Macomb');
INSERT INTO zipcode VALUES('Sterling Heights','MI','48312','Macomb');
INSERT INTO zipcode VALUES('Sterling Heights','MI','48313','Macomb');
INSERT INTO zipcode VALUES('Sterling Heights','MI','48314','Macomb');
INSERT INTO zipcode VALUES('Utica','MI','48315','Macomb');
INSERT INTO zipcode VALUES('Utica','MI','48316','Macomb');
INSERT INTO zipcode VALUES('Utica','MI','48317','Macomb');
INSERT INTO zipcode VALUES('Utica','MI','48318','Macomb');
INSERT INTO zipcode VALUES('Keego Harbor','MI','48320','Oakland');
INSERT INTO zipcode VALUES('Auburn Hills','MI','48321','Oakland');
INSERT INTO zipcode VALUES('West Bloomfield','MI','48322','Oakland');
INSERT INTO zipcode VALUES('West Bloomfield','MI','48323','Oakland');
INSERT INTO zipcode VALUES('West Bloomfield','MI','48324','Oakland');
INSERT INTO zipcode VALUES('West Bloomfield','MI','48325','Oakland');
INSERT INTO zipcode VALUES('Auburn Hills','MI','48326','Oakland');
INSERT INTO zipcode VALUES('Waterford','MI','48327','Oakland');
INSERT INTO zipcode VALUES('Waterford','MI','48328','Oakland');
INSERT INTO zipcode VALUES('Waterford','MI','48329','Oakland');
INSERT INTO zipcode VALUES('Drayton Plains','MI','48330','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48331','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48332','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48333','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48334','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48335','Oakland');
INSERT INTO zipcode VALUES('Farmington','MI','48336','Oakland');
INSERT INTO zipcode VALUES('Pontiac','MI','48340','Oakland');
INSERT INTO zipcode VALUES('Pontiac','MI','48341','Oakland');
INSERT INTO zipcode VALUES('Pontiac','MI','48342','Oakland');
INSERT INTO zipcode VALUES('Pontiac','MI','48343','Oakland');
INSERT INTO zipcode VALUES('Clarkston','MI','48346','Oakland');
INSERT INTO zipcode VALUES('Clarkston','MI','48347','Oakland');
INSERT INTO zipcode VALUES('Clarkston','MI','48348','Oakland');
INSERT INTO zipcode VALUES('Davisburg','MI','48350','Oakland');
INSERT INTO zipcode VALUES('Hartland','MI','48353','Livingston');
INSERT INTO zipcode VALUES('Highland','MI','48356','Oakland');
INSERT INTO zipcode VALUES('Highland','MI','48357','Oakland');
INSERT INTO zipcode VALUES('Lake Orion','MI','48359','Oakland');
INSERT INTO zipcode VALUES('Lake Orion','MI','48360','Oakland');
INSERT INTO zipcode VALUES('Lake Orion','MI','48361','Oakland');
INSERT INTO zipcode VALUES('Lake Orion','MI','48362','Oakland');
INSERT INTO zipcode VALUES('Oakland','MI','48363','Oakland');
INSERT INTO zipcode VALUES('Lakeville','MI','48366','Oakland');
INSERT INTO zipcode VALUES('Leonard','MI','48367','Oakland');
INSERT INTO zipcode VALUES('Oxford','MI','48370','Oakland');
INSERT INTO zipcode VALUES('Oxford','MI','48371','Oakland');
INSERT INTO zipcode VALUES('Novi','MI','48374','Oakland');
INSERT INTO zipcode VALUES('Novi','MI','48375','Oakland');
INSERT INTO zipcode VALUES('Novi','MI','48376','Oakland');
INSERT INTO zipcode VALUES('Novi','MI','48377','Oakland');
INSERT INTO zipcode VALUES('Milford','MI','48380','Oakland');
INSERT INTO zipcode VALUES('Milford','MI','48381','Oakland');
INSERT INTO zipcode VALUES('Commerce Township','MI','48382','Oakland');
INSERT INTO zipcode VALUES('White Lake','MI','48383','Oakland');
INSERT INTO zipcode VALUES('White Lake','MI','48386','Oakland');
INSERT INTO zipcode VALUES('Union Lake','MI','48387','Oakland');
INSERT INTO zipcode VALUES('Walled Lake','MI','48390','Oakland');
INSERT INTO zipcode VALUES('Walled Lake','MI','48391','Oakland');
INSERT INTO zipcode VALUES('Wixom','MI','48393','Oakland');
INSERT INTO zipcode VALUES('Warren','MI','48397','Macomb');
INSERT INTO zipcode VALUES('Clawson','MI','48398','Oakland');
INSERT INTO zipcode VALUES('Applegate','MI','48401','Sanilac');
INSERT INTO zipcode VALUES('Argyle','MI','48410','Sanilac');
INSERT INTO zipcode VALUES('Atlas','MI','48411','Genesee');
INSERT INTO zipcode VALUES('Attica','MI','48412','Lapeer');
INSERT INTO zipcode VALUES('Bad Axe','MI','48413','Huron');
INSERT INTO zipcode VALUES('Bancroft','MI','48414','Shiawassee');
INSERT INTO zipcode VALUES('Birch Run','MI','48415','Saginaw');
INSERT INTO zipcode VALUES('Brown City','MI','48416','Sanilac');
INSERT INTO zipcode VALUES('Burt','MI','48417','Saginaw');
INSERT INTO zipcode VALUES('Byron','MI','48418','Shiawassee');
INSERT INTO zipcode VALUES('Carsonville','MI','48419','Sanilac');
INSERT INTO zipcode VALUES('Clio','MI','48420','Genesee');
INSERT INTO zipcode VALUES('Columbiaville','MI','48421','Lapeer');
INSERT INTO zipcode VALUES('Croswell','MI','48422','Sanilac');
INSERT INTO zipcode VALUES('Davison','MI','48423','Genesee');
INSERT INTO zipcode VALUES('Decker','MI','48426','Sanilac');
INSERT INTO zipcode VALUES('Deckerville','MI','48427','Sanilac');
INSERT INTO zipcode VALUES('Dryden','MI','48428','Lapeer');
INSERT INTO zipcode VALUES('Durand','MI','48429','Shiawassee');
INSERT INTO zipcode VALUES('Fenton','MI','48430','Genesee');
INSERT INTO zipcode VALUES('Filion','MI','48432','Huron');
INSERT INTO zipcode VALUES('Flushing','MI','48433','Genesee');
INSERT INTO zipcode VALUES('Forestville','MI','48434','Sanilac');
INSERT INTO zipcode VALUES('Fostoria','MI','48435','Tuscola');
INSERT INTO zipcode VALUES('Gaines','MI','48436','Genesee');
INSERT INTO zipcode VALUES('Genesee','MI','48437','Genesee');
INSERT INTO zipcode VALUES('Goodrich','MI','48438','Genesee');
INSERT INTO zipcode VALUES('Grand Blanc','MI','48439','Genesee');
INSERT INTO zipcode VALUES('Hadley','MI','48440','Lapeer');
INSERT INTO zipcode VALUES('Harbor Beach','MI','48441','Huron');
INSERT INTO zipcode VALUES('Holly','MI','48442','Oakland');
INSERT INTO zipcode VALUES('Imlay City','MI','48444','Lapeer');
INSERT INTO zipcode VALUES('Kinde','MI','48445','Huron');
INSERT INTO zipcode VALUES('Lapeer','MI','48446','Lapeer');
INSERT INTO zipcode VALUES('Lennon','MI','48449','Genesee');
INSERT INTO zipcode VALUES('Lexington','MI','48450','Sanilac');
INSERT INTO zipcode VALUES('Linden','MI','48451','Genesee');
INSERT INTO zipcode VALUES('Marlette','MI','48453','Sanilac');
INSERT INTO zipcode VALUES('Melvin','MI','48454','Sanilac');
INSERT INTO zipcode VALUES('Metamora','MI','48455','Lapeer');
INSERT INTO zipcode VALUES('Minden City','MI','48456','Sanilac');
INSERT INTO zipcode VALUES('Montrose','MI','48457','Genesee');
INSERT INTO zipcode VALUES('Mount Morris','MI','48458','Genesee');
INSERT INTO zipcode VALUES('New Lothrop','MI','48460','Shiawassee');
INSERT INTO zipcode VALUES('North Branch','MI','48461','Lapeer');
INSERT INTO zipcode VALUES('Ortonville','MI','48462','Oakland');
INSERT INTO zipcode VALUES('Otisville','MI','48463','Genesee');
INSERT INTO zipcode VALUES('Otter Lake','MI','48464','Lapeer');
INSERT INTO zipcode VALUES('Palms','MI','48465','Sanilac');
INSERT INTO zipcode VALUES('Peck','MI','48466','Sanilac');
INSERT INTO zipcode VALUES('Port Austin','MI','48467','Huron');
INSERT INTO zipcode VALUES('Port Hope','MI','48468','Huron');
INSERT INTO zipcode VALUES('Port Sanilac','MI','48469','Sanilac');
INSERT INTO zipcode VALUES('Ruth','MI','48470','Huron');
INSERT INTO zipcode VALUES('Sandusky','MI','48471','Sanilac');
INSERT INTO zipcode VALUES('Snover','MI','48472','Sanilac');
INSERT INTO zipcode VALUES('Swartz Creek','MI','48473','Genesee');
INSERT INTO zipcode VALUES('Ubly','MI','48475','Huron');
INSERT INTO zipcode VALUES('Vernon','MI','48476','Shiawassee');
INSERT INTO zipcode VALUES('Flint','MI','48501','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48502','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48503','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48504','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48505','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48506','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48507','Genesee');
INSERT INTO zipcode VALUES('Burton','MI','48509','Genesee');
INSERT INTO zipcode VALUES('Burton','MI','48519','Genesee');
INSERT INTO zipcode VALUES('Burton','MI','48529','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48531','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48532','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48550','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48551','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48552','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48553','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48554','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48555','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48556','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48557','Genesee');
INSERT INTO zipcode VALUES('Flint','MI','48559','Genesee');
INSERT INTO zipcode VALUES('Saginaw','MI','48601','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48602','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48603','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48604','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48605','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48606','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48607','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48608','Saginaw');
INSERT INTO zipcode VALUES('Saginaw','MI','48609','Saginaw');
INSERT INTO zipcode VALUES('Alger','MI','48610','Arenac');
INSERT INTO zipcode VALUES('Auburn','MI','48611','Bay');
INSERT INTO zipcode VALUES('Beaverton','MI','48612','Gladwin');
INSERT INTO zipcode VALUES('Bentley','MI','48613','Bay');
INSERT INTO zipcode VALUES('Brant','MI','48614','Saginaw');
INSERT INTO zipcode VALUES('Breckenridge','MI','48615','Gratiot');
INSERT INTO zipcode VALUES('Chesaning','MI','48616','Saginaw');
INSERT INTO zipcode VALUES('Clare','MI','48617','Clare');
INSERT INTO zipcode VALUES('Coleman','MI','48618','Midland');
INSERT INTO zipcode VALUES('Comins','MI','48619','Oscoda');
INSERT INTO zipcode VALUES('Edenville','MI','48620','Midland');
INSERT INTO zipcode VALUES('Fairview','MI','48621','Oscoda');
INSERT INTO zipcode VALUES('Farwell','MI','48622','Clare');
INSERT INTO zipcode VALUES('Freeland','MI','48623','Saginaw');
INSERT INTO zipcode VALUES('Gladwin','MI','48624','Gladwin');
INSERT INTO zipcode VALUES('Harrison','MI','48625','Clare');
INSERT INTO zipcode VALUES('Hemlock','MI','48626','Saginaw');
INSERT INTO zipcode VALUES('Higgins Lake','MI','48627','Roscommon');
INSERT INTO zipcode VALUES('Hope','MI','48628','Midland');
INSERT INTO zipcode VALUES('Houghton Lake','MI','48629','Roscommon');
INSERT INTO zipcode VALUES('Houghton Lake','MI','48630','Michigan Roscommon');
INSERT INTO zipcode VALUES('Kawkawlin','MI','48631','Bay');
INSERT INTO zipcode VALUES('Lake','MI','48632','Clare');
INSERT INTO zipcode VALUES('Lake George','MI','48633','Clare');
INSERT INTO zipcode VALUES('Linwood','MI','48634','Bay');
INSERT INTO zipcode VALUES('Lupton','MI','48635','Ogemaw');
INSERT INTO zipcode VALUES('Luzerne','MI','48636','Oscoda');
INSERT INTO zipcode VALUES('Merrill','MI','48637','Saginaw');
INSERT INTO zipcode VALUES('Midland','MI','48640','Midland');
INSERT INTO zipcode VALUES('Midland','MI','48641','Midland');
INSERT INTO zipcode VALUES('Midland','MI','48642','Midland');
INSERT INTO zipcode VALUES('Mio','MI','48647','Oscoda');
INSERT INTO zipcode VALUES('Oakley','MI','48649','Saginaw');
INSERT INTO zipcode VALUES('Pinconning','MI','48650','Bay');
INSERT INTO zipcode VALUES('Prudenville','MI','48651','Roscommon');
INSERT INTO zipcode VALUES('Rhodes','MI','48652','Gladwin');
INSERT INTO zipcode VALUES('Roscommon','MI','48653','Roscommon');
INSERT INTO zipcode VALUES('Rose City','MI','48654','Ogemaw');
INSERT INTO zipcode VALUES('Saint Charles','MI','48655','Saginaw');
INSERT INTO zipcode VALUES('Saint Helen','MI','48656','Roscommon');
INSERT INTO zipcode VALUES('Sanford','MI','48657','Midland');
INSERT INTO zipcode VALUES('Standish','MI','48658','Arenac');
INSERT INTO zipcode VALUES('Sterling','MI','48659','Arenac');
INSERT INTO zipcode VALUES('West Branch','MI','48661','Ogemaw');
INSERT INTO zipcode VALUES('Wheeler','MI','48662','Gratiot');
INSERT INTO zipcode VALUES('Saginaw','MI','48663','Saginaw');
INSERT INTO zipcode VALUES('Midland','MI','48667','Midland');
INSERT INTO zipcode VALUES('Midland','MI','48670','Midland');
INSERT INTO zipcode VALUES('Midland','MI','48674','Midland');
INSERT INTO zipcode VALUES('Midland','MI','48686','Midland');
INSERT INTO zipcode VALUES('Akron','MI','48701','Tuscola');
INSERT INTO zipcode VALUES('Au Gres','MI','48703','Arenac');
INSERT INTO zipcode VALUES('Barton City','MI','48705','Alcona');
INSERT INTO zipcode VALUES('Bay City','MI','48706','Bay');
INSERT INTO zipcode VALUES('Bay City','MI','48707','Bay');
INSERT INTO zipcode VALUES('Bay City','MI','48708','Bay');
INSERT INTO zipcode VALUES('University Center','MI','48710','Bay');
INSERT INTO zipcode VALUES('Bay Port','MI','48720','Huron');
INSERT INTO zipcode VALUES('Black River','MI','48721','Alcona');
INSERT INTO zipcode VALUES('Bridgeport','MI','48722','Saginaw');
INSERT INTO zipcode VALUES('Caro','MI','48723','Tuscola');
INSERT INTO zipcode VALUES('Carrollton','MI','48724','Saginaw');
INSERT INTO zipcode VALUES('Caseville','MI','48725','Huron');
INSERT INTO zipcode VALUES('Cass City','MI','48726','Tuscola');
INSERT INTO zipcode VALUES('Clifford','MI','48727','Lapeer');
INSERT INTO zipcode VALUES('Curran','MI','48728','Alcona');
INSERT INTO zipcode VALUES('Deford','MI','48729','Tuscola');
INSERT INTO zipcode VALUES('East Tawas','MI','48730','Iosco');
INSERT INTO zipcode VALUES('Elkton','MI','48731','Huron');
INSERT INTO zipcode VALUES('Essexville','MI','48732','Bay');
INSERT INTO zipcode VALUES('Fairgrove','MI','48733','Tuscola');
INSERT INTO zipcode VALUES('Frankenmuth','MI','48734','Saginaw');
INSERT INTO zipcode VALUES('Gagetown','MI','48735','Tuscola');
INSERT INTO zipcode VALUES('Gilford','MI','48736','Tuscola');
INSERT INTO zipcode VALUES('Glennie','MI','48737','Alcona');
INSERT INTO zipcode VALUES('Greenbush','MI','48738','Alcona');
INSERT INTO zipcode VALUES('Hale','MI','48739','Iosco');
INSERT INTO zipcode VALUES('Harrisville','MI','48740','Alcona');
INSERT INTO zipcode VALUES('Kingston','MI','48741','Tuscola');
INSERT INTO zipcode VALUES('Lincoln','MI','48742','Alcona');
INSERT INTO zipcode VALUES('Long Lake','MI','48743','Iosco');
INSERT INTO zipcode VALUES('Mayville','MI','48744','Tuscola');
INSERT INTO zipcode VALUES('Mikado','MI','48745','Alcona');
INSERT INTO zipcode VALUES('Millington','MI','48746','Tuscola');
INSERT INTO zipcode VALUES('Munger','MI','48747','Bay');
INSERT INTO zipcode VALUES('National City','MI','48748','Iosco');
INSERT INTO zipcode VALUES('Omer','MI','48749','Arenac');
INSERT INTO zipcode VALUES('Oscoda','MI','48750','Iosco');
INSERT INTO zipcode VALUES('Owendale','MI','48754','Huron');
INSERT INTO zipcode VALUES('Pigeon','MI','48755','Huron');
INSERT INTO zipcode VALUES('Prescott','MI','48756','Ogemaw');
INSERT INTO zipcode VALUES('Reese','MI','48757','Tuscola');
INSERT INTO zipcode VALUES('Richville','MI','48758','Tuscola');
INSERT INTO zipcode VALUES('Sebewaing','MI','48759','Huron');
INSERT INTO zipcode VALUES('Silverwood','MI','48760','Tuscola');
INSERT INTO zipcode VALUES('South Branch','MI','48761','Ogemaw');
INSERT INTO zipcode VALUES('Spruce','MI','48762','Alcona');
INSERT INTO zipcode VALUES('Tawas City','MI','48763','Iosco');
INSERT INTO zipcode VALUES('Tawas City','MI','48764','Iosco');
INSERT INTO zipcode VALUES('Turner','MI','48765','Arenac');
INSERT INTO zipcode VALUES('Twining','MI','48766','Arenac');
INSERT INTO zipcode VALUES('Unionville','MI','48767','Tuscola');
INSERT INTO zipcode VALUES('Vassar','MI','48768','Tuscola');
INSERT INTO zipcode VALUES('Tuscola','MI','48769','Tuscola');
INSERT INTO zipcode VALUES('Whittemore','MI','48770','Iosco');
INSERT INTO zipcode VALUES('Frankenmuth','MI','48787','Saginaw');
INSERT INTO zipcode VALUES('Alma','MI','48801','Gratiot');
INSERT INTO zipcode VALUES('Alma','MI','48802','Gratiot');
INSERT INTO zipcode VALUES('Mount Pleasant','MI','48804','Isabella');
INSERT INTO zipcode VALUES('Okemos','MI','48805','Ingham');
INSERT INTO zipcode VALUES('Ashley','MI','48806','Gratiot');
INSERT INTO zipcode VALUES('Bannister','MI','48807','Gratiot');
INSERT INTO zipcode VALUES('Bath','MI','48808','Clinton');
INSERT INTO zipcode VALUES('Belding','MI','48809','Ionia');
INSERT INTO zipcode VALUES('Carson City','MI','48811','Montcalm');
INSERT INTO zipcode VALUES('Cedar Lake','MI','48812','Montcalm');
INSERT INTO zipcode VALUES('Charlotte','MI','48813','Eaton');
INSERT INTO zipcode VALUES('Clarksville','MI','48815','Ionia');
INSERT INTO zipcode VALUES('Cohoctah','MI','48816','Livingston');
INSERT INTO zipcode VALUES('Corunna','MI','48817','Shiawassee');
INSERT INTO zipcode VALUES('Crystal','MI','48818','Montcalm');
INSERT INTO zipcode VALUES('Dansville','MI','48819','Ingham');
INSERT INTO zipcode VALUES('Dewitt','MI','48820','Clinton');
INSERT INTO zipcode VALUES('Dimondale','MI','48821','Eaton');
INSERT INTO zipcode VALUES('Eagle','MI','48822','Clinton');
INSERT INTO zipcode VALUES('East Lansing','MI','48823','Ingham');
INSERT INTO zipcode VALUES('East Lansing','MI','48824','Ingham');
INSERT INTO zipcode VALUES('East Lansing','MI','48825','Ingham');
INSERT INTO zipcode VALUES('East Lansing','MI','48826','Ingham');
INSERT INTO zipcode VALUES('Eaton Rapids','MI','48827','Eaton');
INSERT INTO zipcode VALUES('Edmore','MI','48829','Montcalm');
INSERT INTO zipcode VALUES('Elm Hall','MI','48830','Gratiot');
INSERT INTO zipcode VALUES('Elsie','MI','48831','Clinton');
INSERT INTO zipcode VALUES('Elwell','MI','48832','Gratiot');
INSERT INTO zipcode VALUES('Eureka','MI','48833','Clinton');
INSERT INTO zipcode VALUES('Fenwick','MI','48834','Montcalm');
INSERT INTO zipcode VALUES('Fowler','MI','48835','Clinton');
INSERT INTO zipcode VALUES('Fowlerville','MI','48836','Livingston');
INSERT INTO zipcode VALUES('Grand Ledge','MI','48837','Eaton');
INSERT INTO zipcode VALUES('Greenville','MI','48838','Montcalm');
INSERT INTO zipcode VALUES('Haslett','MI','48840','Ingham');
INSERT INTO zipcode VALUES('Henderson','MI','48841','Shiawassee');
INSERT INTO zipcode VALUES('Holt','MI','48842','Ingham');
INSERT INTO zipcode VALUES('Howell','MI','48843','Livingston');
INSERT INTO zipcode VALUES('Howell','MI','48844','Livingston');
INSERT INTO zipcode VALUES('Hubbardston','MI','48845','Ionia');
INSERT INTO zipcode VALUES('Ionia','MI','48846','Ionia');
INSERT INTO zipcode VALUES('Ithaca','MI','48847','Gratiot');
INSERT INTO zipcode VALUES('Laingsburg','MI','48848','Shiawassee');
INSERT INTO zipcode VALUES('Lake Odessa','MI','48849','Ionia');
INSERT INTO zipcode VALUES('Lakeview','MI','48850','Montcalm');
INSERT INTO zipcode VALUES('Lyons','MI','48851','Ionia');
INSERT INTO zipcode VALUES('McBrides','MI','48852','Montcalm');
INSERT INTO zipcode VALUES('Maple Rapids','MI','48853','Clinton');
INSERT INTO zipcode VALUES('Mason','MI','48854','Ingham');
INSERT INTO zipcode VALUES('Middleton','MI','48856','Gratiot');
INSERT INTO zipcode VALUES('Morrice','MI','48857','Shiawassee');
INSERT INTO zipcode VALUES('Mount Pleasant','MI','48858','Isabella');
INSERT INTO zipcode VALUES('Mount Pleasant','MI','48859','Isabella');
INSERT INTO zipcode VALUES('Muir','MI','48860','Ionia');
INSERT INTO zipcode VALUES('Mulliken','MI','48861','Eaton');
INSERT INTO zipcode VALUES('North Star','MI','48862','Gratiot');
INSERT INTO zipcode VALUES('Oak Grove','MI','48863','Livingston');
INSERT INTO zipcode VALUES('Okemos','MI','48864','Ingham');
INSERT INTO zipcode VALUES('Orleans','MI','48865','Ionia');
INSERT INTO zipcode VALUES('Ovid','MI','48866','Clinton');
INSERT INTO zipcode VALUES('Owosso','MI','48867','Shiawassee');
INSERT INTO zipcode VALUES('Palo','MI','48870','Ionia');
INSERT INTO zipcode VALUES('Perrinton','MI','48871','Gratiot');
INSERT INTO zipcode VALUES('Perry','MI','48872','Shiawassee');
INSERT INTO zipcode VALUES('Pewamo','MI','48873','Ionia');
INSERT INTO zipcode VALUES('Pompeii','MI','48874','Gratiot');
INSERT INTO zipcode VALUES('Portland','MI','48875','Ionia');
INSERT INTO zipcode VALUES('Potterville','MI','48876','Eaton');
INSERT INTO zipcode VALUES('Riverdale','MI','48877','Gratiot');
INSERT INTO zipcode VALUES('Rosebush','MI','48878','Isabella');
INSERT INTO zipcode VALUES('Saint Johns','MI','48879','Clinton');
INSERT INTO zipcode VALUES('Saint Louis','MI','48880','Gratiot');
INSERT INTO zipcode VALUES('Saranac','MI','48881','Ionia');
INSERT INTO zipcode VALUES('Shaftsburg','MI','48882','Shiawassee');
INSERT INTO zipcode VALUES('Shepherd','MI','48883','Isabella');
INSERT INTO zipcode VALUES('Sheridan','MI','48884','Montcalm');
INSERT INTO zipcode VALUES('Sidney','MI','48885','Montcalm');
INSERT INTO zipcode VALUES('Six Lakes','MI','48886','Montcalm');
INSERT INTO zipcode VALUES('Smyrna','MI','48887','Ionia');
INSERT INTO zipcode VALUES('Stanton','MI','48888','Montcalm');
INSERT INTO zipcode VALUES('Sumner','MI','48889','Gratiot');
INSERT INTO zipcode VALUES('Sunfield','MI','48890','Eaton');
INSERT INTO zipcode VALUES('Vestaburg','MI','48891','Montcalm');
INSERT INTO zipcode VALUES('Webberville','MI','48892','Ingham');
INSERT INTO zipcode VALUES('Weidman','MI','48893','Isabella');
INSERT INTO zipcode VALUES('Westphalia','MI','48894','Clinton');
INSERT INTO zipcode VALUES('Williamston','MI','48895','Ingham');
INSERT INTO zipcode VALUES('Winn','MI','48896','Isabella');
INSERT INTO zipcode VALUES('Woodland','MI','48897','Barry');
INSERT INTO zipcode VALUES('Lansing','MI','48901','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48906','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48907','Eaton');
INSERT INTO zipcode VALUES('Lansing','MI','48908','Eaton');
INSERT INTO zipcode VALUES('Lansing','MI','48909','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48910','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48911','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48912','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48913','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48915','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48916','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48917','Eaton');
INSERT INTO zipcode VALUES('Lansing','MI','48918','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48919','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48921','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48922','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48924','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48929','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48930','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48933','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48937','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48950','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48956','Ingham');
INSERT INTO zipcode VALUES('Lansing','MI','48980','Ingham');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49001','Kalamazoo');
INSERT INTO zipcode VALUES('Portage','MI','49002','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49003','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49004','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49005','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49006','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49007','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49008','Kalamazoo');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49009','Kalamazoo');
INSERT INTO zipcode VALUES('Allegan','MI','49010','Allegan');
INSERT INTO zipcode VALUES('Athens','MI','49011','Calhoun');
INSERT INTO zipcode VALUES('Augusta','MI','49012','Kalamazoo');
INSERT INTO zipcode VALUES('Bangor','MI','49013','Van Buren');
INSERT INTO zipcode VALUES('Battle Creek','MI','49014','Calhoun');
INSERT INTO zipcode VALUES('Battle Creek','MI','49015','Calhoun');
INSERT INTO zipcode VALUES('Battle Creek','MI','49016','Calhoun');
INSERT INTO zipcode VALUES('Battle Creek','MI','49017','Calhoun');
INSERT INTO zipcode VALUES('Battle Creek','MI','49018','Calhoun');
INSERT INTO zipcode VALUES('Kalamazoo','MI','49019','Kalamazoo');
INSERT INTO zipcode VALUES('Bedford','MI','49020','Calhoun');
INSERT INTO zipcode VALUES('Bellevue','MI','49021','Eaton');
INSERT INTO zipcode VALUES('Benton Harbor','MI','49022','Berrien');
INSERT INTO zipcode VALUES('Benton Harbor','MI','49023','Berrien');
INSERT INTO zipcode VALUES('Portage','MI','49024','Kalamazoo');
INSERT INTO zipcode VALUES('Bloomingdale','MI','49026','Van Buren');
INSERT INTO zipcode VALUES('Breedsville','MI','49027','Van Buren');
INSERT INTO zipcode VALUES('Bronson','MI','49028','Branch');
INSERT INTO zipcode VALUES('Burlington','MI','49029','Calhoun');
INSERT INTO zipcode VALUES('Burr Oak','MI','49030','Saint Joseph');
INSERT INTO zipcode VALUES('Cassopolis','MI','49031','Cass');
INSERT INTO zipcode VALUES('Centreville','MI','49032','Saint Joseph');
INSERT INTO zipcode VALUES('Ceresco','MI','49033','Calhoun');
INSERT INTO zipcode VALUES('Climax','MI','49034','Kalamazoo');
INSERT INTO zipcode VALUES('Cloverdale','MI','49035','Barry');
INSERT INTO zipcode VALUES('Coldwater','MI','49036','Branch');
INSERT INTO zipcode VALUES('Coloma','MI','49038','Berrien');
INSERT INTO zipcode VALUES('Hagar Shores','MI','49039','Berrien');
INSERT INTO zipcode VALUES('Colon','MI','49040','Saint Joseph');
INSERT INTO zipcode VALUES('Comstock','MI','49041','Kalamazoo');
INSERT INTO zipcode VALUES('Constantine','MI','49042','Saint Joseph');
INSERT INTO zipcode VALUES('Covert','MI','49043','Van Buren');
INSERT INTO zipcode VALUES('Decatur','MI','49045','Van Buren');
INSERT INTO zipcode VALUES('Delton','MI','49046','Barry');
INSERT INTO zipcode VALUES('Dowagiac','MI','49047','Cass');
INSERT INTO zipcode VALUES('Dowling','MI','49050','Barry');
INSERT INTO zipcode VALUES('East Leroy','MI','49051','Calhoun');
INSERT INTO zipcode VALUES('Fulton','MI','49052','Kalamazoo');
INSERT INTO zipcode VALUES('Galesburg','MI','49053','Kalamazoo');
INSERT INTO zipcode VALUES('Gobles','MI','49055','Van Buren');
INSERT INTO zipcode VALUES('Grand Junction','MI','49056','Van Buren');
INSERT INTO zipcode VALUES('Hartford','MI','49057','Van Buren');
INSERT INTO zipcode VALUES('Hastings','MI','49058','Barry');
INSERT INTO zipcode VALUES('Hickory Corners','MI','49060','Barry');
INSERT INTO zipcode VALUES('Jones','MI','49061','Cass');
INSERT INTO zipcode VALUES('Kendall','MI','49062','Van Buren');
INSERT INTO zipcode VALUES('Lacota','MI','49063','Van Buren');
INSERT INTO zipcode VALUES('Lawrence','MI','49064','Van Buren');
INSERT INTO zipcode VALUES('Lawton','MI','49065','Van Buren');
INSERT INTO zipcode VALUES('Leonidas','MI','49066','Saint Joseph');
INSERT INTO zipcode VALUES('Marcellus','MI','49067','Cass');
INSERT INTO zipcode VALUES('Marshall','MI','49068','Calhoun');
INSERT INTO zipcode VALUES('Marshall','MI','49069','Calhoun');
INSERT INTO zipcode VALUES('Martin','MI','49070','Allegan');
INSERT INTO zipcode VALUES('Mattawan','MI','49071','Van Buren');
INSERT INTO zipcode VALUES('Mendon','MI','49072','Saint Joseph');
INSERT INTO zipcode VALUES('Nashville','MI','49073','Barry');
INSERT INTO zipcode VALUES('Nazareth','MI','49074','Kalamazoo');
INSERT INTO zipcode VALUES('Nottawa','MI','49075','Saint Joseph');
INSERT INTO zipcode VALUES('Olivet','MI','49076','Eaton');
INSERT INTO zipcode VALUES('Oshtemo','MI','49077','Kalamazoo');
INSERT INTO zipcode VALUES('Otsego','MI','49078','Allegan');
INSERT INTO zipcode VALUES('Paw Paw','MI','49079','Van Buren');
INSERT INTO zipcode VALUES('Plainwell','MI','49080','Allegan');
INSERT INTO zipcode VALUES('Portage','MI','49081','Kalamazoo');
INSERT INTO zipcode VALUES('Quincy','MI','49082','Branch');
INSERT INTO zipcode VALUES('Richland','MI','49083','Kalamazoo');
INSERT INTO zipcode VALUES('Riverside','MI','49084','Berrien');
INSERT INTO zipcode VALUES('Saint Joseph','MI','49085','Berrien');
INSERT INTO zipcode VALUES('Schoolcraft','MI','49087','Kalamazoo');
INSERT INTO zipcode VALUES('Scotts','MI','49088','Kalamazoo');
INSERT INTO zipcode VALUES('Sherwood','MI','49089','Branch');
INSERT INTO zipcode VALUES('South Haven','MI','49090','Van Buren');
INSERT INTO zipcode VALUES('Sturgis','MI','49091','Saint Joseph');
INSERT INTO zipcode VALUES('Tekonsha','MI','49092','Calhoun');
INSERT INTO zipcode VALUES('Three Rivers','MI','49093','Saint Joseph');
INSERT INTO zipcode VALUES('Union City','MI','49094','Branch');
INSERT INTO zipcode VALUES('Vandalia','MI','49095','Cass');
INSERT INTO zipcode VALUES('Vermontville','MI','49096','Eaton');
INSERT INTO zipcode VALUES('Vicksburg','MI','49097','Kalamazoo');
INSERT INTO zipcode VALUES('Watervliet','MI','49098','Berrien');
INSERT INTO zipcode VALUES('White Pigeon','MI','49099','Saint Joseph');
INSERT INTO zipcode VALUES('Baroda','MI','49101','Berrien');
INSERT INTO zipcode VALUES('Berrien Center','MI','49102','Berrien');
INSERT INTO zipcode VALUES('Berrien Springs','MI','49103','Berrien');
INSERT INTO zipcode VALUES('Berrien Springs','MI','49104','Berrien');
INSERT INTO zipcode VALUES('Bridgman','MI','49106','Berrien');
INSERT INTO zipcode VALUES('Buchanan','MI','49107','Berrien');
INSERT INTO zipcode VALUES('Eau Claire','MI','49111','Berrien');
INSERT INTO zipcode VALUES('Edwardsburg','MI','49112','Cass');
INSERT INTO zipcode VALUES('Galien','MI','49113','Berrien');
INSERT INTO zipcode VALUES('Harbert','MI','49115','Berrien');
INSERT INTO zipcode VALUES('Lakeside','MI','49116','Berrien');
INSERT INTO zipcode VALUES('New Buffalo','MI','49117','Berrien');
INSERT INTO zipcode VALUES('New Troy','MI','49119','Berrien');
INSERT INTO zipcode VALUES('Niles','MI','49120','Berrien');
INSERT INTO zipcode VALUES('Niles','MI','49121','Berrien');
INSERT INTO zipcode VALUES('Sawyer','MI','49125','Berrien');
INSERT INTO zipcode VALUES('Sodus','MI','49126','Berrien');
INSERT INTO zipcode VALUES('Stevensville','MI','49127','Berrien');
INSERT INTO zipcode VALUES('Three Oaks','MI','49128','Berrien');
INSERT INTO zipcode VALUES('Union Pier','MI','49129','Berrien');
INSERT INTO zipcode VALUES('Union','MI','49130','Cass');
INSERT INTO zipcode VALUES('Jackson','MI','49201','Jackson');
INSERT INTO zipcode VALUES('Jackson','MI','49202','Jackson');
INSERT INTO zipcode VALUES('Jackson','MI','49203','Jackson');
INSERT INTO zipcode VALUES('Jackson','MI','49204','Jackson');
INSERT INTO zipcode VALUES('Addison','MI','49220','Lenawee');
INSERT INTO zipcode VALUES('Adrian','MI','49221','Lenawee');
INSERT INTO zipcode VALUES('Albion','MI','49224','Calhoun');
INSERT INTO zipcode VALUES('Allen','MI','49227','Hillsdale');
INSERT INTO zipcode VALUES('Blissfield','MI','49228','Lenawee');
INSERT INTO zipcode VALUES('Britton','MI','49229','Lenawee');
INSERT INTO zipcode VALUES('Brooklyn','MI','49230','Jackson');
INSERT INTO zipcode VALUES('Camden','MI','49232','Hillsdale');
INSERT INTO zipcode VALUES('Cement City','MI','49233','Lenawee');
INSERT INTO zipcode VALUES('Clarklake','MI','49234','Jackson');
INSERT INTO zipcode VALUES('Clayton','MI','49235','Lenawee');
INSERT INTO zipcode VALUES('Clinton','MI','49236','Lenawee');
INSERT INTO zipcode VALUES('Concord','MI','49237','Jackson');
INSERT INTO zipcode VALUES('Deerfield','MI','49238','Lenawee');
INSERT INTO zipcode VALUES('Frontier','MI','49239','Hillsdale');
INSERT INTO zipcode VALUES('Grass Lake','MI','49240','Jackson');
INSERT INTO zipcode VALUES('Hanover','MI','49241','Jackson');
INSERT INTO zipcode VALUES('Hillsdale','MI','49242','Hillsdale');
INSERT INTO zipcode VALUES('Homer','MI','49245','Calhoun');
INSERT INTO zipcode VALUES('Horton','MI','49246','Jackson');
INSERT INTO zipcode VALUES('Hudson','MI','49247','Lenawee');
INSERT INTO zipcode VALUES('Jasper','MI','49248','Lenawee');
INSERT INTO zipcode VALUES('Jerome','MI','49249','Hillsdale');
INSERT INTO zipcode VALUES('Jonesville','MI','49250','Hillsdale');
INSERT INTO zipcode VALUES('Leslie','MI','49251','Ingham');
INSERT INTO zipcode VALUES('Litchfield','MI','49252','Hillsdale');
INSERT INTO zipcode VALUES('Manitou Beach','MI','49253','Lenawee');
INSERT INTO zipcode VALUES('Michigan Center','MI','49254','Jackson');
INSERT INTO zipcode VALUES('Montgomery','MI','49255','Branch');
INSERT INTO zipcode VALUES('Morenci','MI','49256','Lenawee');
INSERT INTO zipcode VALUES('Moscow','MI','49257','Hillsdale');
INSERT INTO zipcode VALUES('Mosherville','MI','49258','Hillsdale');
INSERT INTO zipcode VALUES('Munith','MI','49259','Jackson');
INSERT INTO zipcode VALUES('Napoleon','MI','49261','Jackson');
INSERT INTO zipcode VALUES('North Adams','MI','49262','Hillsdale');
INSERT INTO zipcode VALUES('Norvell','MI','49263','Jackson');
INSERT INTO zipcode VALUES('Onondaga','MI','49264','Ingham');
INSERT INTO zipcode VALUES('Onsted','MI','49265','Lenawee');
INSERT INTO zipcode VALUES('Osseo','MI','49266','Hillsdale');
INSERT INTO zipcode VALUES('Ottawa Lake','MI','49267','Monroe');
INSERT INTO zipcode VALUES('Palmyra','MI','49268','Lenawee');
INSERT INTO zipcode VALUES('Parma','MI','49269','Jackson');
INSERT INTO zipcode VALUES('Petersburg','MI','49270','Monroe');
INSERT INTO zipcode VALUES('Pittsford','MI','49271','Hillsdale');
INSERT INTO zipcode VALUES('Pleasant Lake','MI','49272','Jackson');
INSERT INTO zipcode VALUES('Reading','MI','49274','Hillsdale');
INSERT INTO zipcode VALUES('Ridgeway','MI','49275','Lenawee');
INSERT INTO zipcode VALUES('Riga','MI','49276','Lenawee');
INSERT INTO zipcode VALUES('Rives Junction','MI','49277','Jackson');
INSERT INTO zipcode VALUES('Rollin','MI','49278','Lenawee');
INSERT INTO zipcode VALUES('Sand Creek','MI','49279','Lenawee');
INSERT INTO zipcode VALUES('Seneca','MI','49280','Lenawee');
INSERT INTO zipcode VALUES('Somerset','MI','49281','Hillsdale');
INSERT INTO zipcode VALUES('Somerset Center','MI','49282','Hillsdale');
INSERT INTO zipcode VALUES('Spring Arbor','MI','49283','Jackson');
INSERT INTO zipcode VALUES('Springport','MI','49284','Jackson');
INSERT INTO zipcode VALUES('Stockbridge','MI','49285','Ingham');
INSERT INTO zipcode VALUES('Tecumseh','MI','49286','Lenawee');
INSERT INTO zipcode VALUES('Tipton','MI','49287','Lenawee');
INSERT INTO zipcode VALUES('Waldron','MI','49288','Hillsdale');
INSERT INTO zipcode VALUES('Weston','MI','49289','Lenawee');
INSERT INTO zipcode VALUES('Ada','MI','49301','Kent');
INSERT INTO zipcode VALUES('Alto','MI','49302','Kent');
INSERT INTO zipcode VALUES('Bailey','MI','49303','Muskegon');
INSERT INTO zipcode VALUES('Baldwin','MI','49304','Lake');
INSERT INTO zipcode VALUES('Barryton','MI','49305','Mecosta');
INSERT INTO zipcode VALUES('Belmont','MI','49306','Kent');
INSERT INTO zipcode VALUES('Big Rapids','MI','49307','Mecosta');
INSERT INTO zipcode VALUES('Bitely','MI','49309','Newaygo');
INSERT INTO zipcode VALUES('Blanchard','MI','49310','Isabella');
INSERT INTO zipcode VALUES('Bradley','MI','49311','Allegan');
INSERT INTO zipcode VALUES('Brohman','MI','49312','Newaygo');
INSERT INTO zipcode VALUES('Burnips','MI','49314','Allegan');
INSERT INTO zipcode VALUES('Byron Center','MI','49315','Kent');
INSERT INTO zipcode VALUES('Caledonia','MI','49316','Kent');
INSERT INTO zipcode VALUES('Cannonsburg','MI','49317','Kent');
INSERT INTO zipcode VALUES('Casnovia','MI','49318','Muskegon');
INSERT INTO zipcode VALUES('Cedar Springs','MI','49319','Kent');
INSERT INTO zipcode VALUES('Chippewa Lake','MI','49320','Mecosta');
INSERT INTO zipcode VALUES('Comstock Park','MI','49321','Kent');
INSERT INTO zipcode VALUES('Coral','MI','49322','Montcalm');
INSERT INTO zipcode VALUES('Dorr','MI','49323','Allegan');
INSERT INTO zipcode VALUES('Freeport','MI','49325','Barry');
INSERT INTO zipcode VALUES('Gowen','MI','49326','Kent');
INSERT INTO zipcode VALUES('Grant','MI','49327','Newaygo');
INSERT INTO zipcode VALUES('Hopkins','MI','49328','Allegan');
INSERT INTO zipcode VALUES('Howard City','MI','49329','Montcalm');
INSERT INTO zipcode VALUES('Kent City','MI','49330','Kent');
INSERT INTO zipcode VALUES('Lowell','MI','49331','Kent');
INSERT INTO zipcode VALUES('Mecosta','MI','49332','Mecosta');
INSERT INTO zipcode VALUES('Middleville','MI','49333','Barry');
INSERT INTO zipcode VALUES('Moline','MI','49335','Allegan');
INSERT INTO zipcode VALUES('Morley','MI','49336','Mecosta');
INSERT INTO zipcode VALUES('Newaygo','MI','49337','Newaygo');
INSERT INTO zipcode VALUES('Paris','MI','49338','Mecosta');
INSERT INTO zipcode VALUES('Pierson','MI','49339','Montcalm');
INSERT INTO zipcode VALUES('Remus','MI','49340','Mecosta');
INSERT INTO zipcode VALUES('Rockford','MI','49341','Kent');
INSERT INTO zipcode VALUES('Rodney','MI','49342','Mecosta');
INSERT INTO zipcode VALUES('Sand Lake','MI','49343','Kent');
INSERT INTO zipcode VALUES('Shelbyville','MI','49344','Allegan');
INSERT INTO zipcode VALUES('Sparta','MI','49345','Kent');
INSERT INTO zipcode VALUES('Stanwood','MI','49346','Mecosta');
INSERT INTO zipcode VALUES('Trufant','MI','49347','Montcalm');
INSERT INTO zipcode VALUES('Wayland','MI','49348','Allegan');
INSERT INTO zipcode VALUES('White Cloud','MI','49349','Newaygo');
INSERT INTO zipcode VALUES('Rockford','MI','49351','Kent');
INSERT INTO zipcode VALUES('Ada','MI','49355','Kent');
INSERT INTO zipcode VALUES('Ada','MI','49356','Kent');
INSERT INTO zipcode VALUES('Ada','MI','49357','Kent');
INSERT INTO zipcode VALUES('Allendale','MI','49401','Ottawa');
INSERT INTO zipcode VALUES('Branch','MI','49402','Mason');
INSERT INTO zipcode VALUES('Conklin','MI','49403','Ottawa');
INSERT INTO zipcode VALUES('Coopersville','MI','49404','Ottawa');
INSERT INTO zipcode VALUES('Custer','MI','49405','Mason');
INSERT INTO zipcode VALUES('Douglas','MI','49406','Allegan');
INSERT INTO zipcode VALUES('Fennville','MI','49408','Allegan');
INSERT INTO zipcode VALUES('Ferrysburg','MI','49409','Ottawa');
INSERT INTO zipcode VALUES('Fountain','MI','49410','Mason');
INSERT INTO zipcode VALUES('Free Soil','MI','49411','Mason');
INSERT INTO zipcode VALUES('Fremont','MI','49412','Newaygo');
INSERT INTO zipcode VALUES('Fremont','MI','49413','Newaygo');
INSERT INTO zipcode VALUES('Fruitport','MI','49415','Muskegon');
INSERT INTO zipcode VALUES('Glenn','MI','49416','Allegan');
INSERT INTO zipcode VALUES('Grand Haven','MI','49417','Ottawa');
INSERT INTO zipcode VALUES('Grandville','MI','49418','Kent');
INSERT INTO zipcode VALUES('Hamilton','MI','49419','Allegan');
INSERT INTO zipcode VALUES('Hart','MI','49420','Oceana');
INSERT INTO zipcode VALUES('Hesperia','MI','49421','Oceana');
INSERT INTO zipcode VALUES('Holland','MI','49422','Ottawa');
INSERT INTO zipcode VALUES('Holland','MI','49423','Ottawa');
INSERT INTO zipcode VALUES('Holland','MI','49424','Ottawa');
INSERT INTO zipcode VALUES('Holton','MI','49425','Muskegon');
INSERT INTO zipcode VALUES('Hudsonville','MI','49426','Ottawa');
INSERT INTO zipcode VALUES('Jamestown','MI','49427','Ottawa');
INSERT INTO zipcode VALUES('Jenison','MI','49428','Ottawa');
INSERT INTO zipcode VALUES('Jenison','MI','49429','Ottawa');
INSERT INTO zipcode VALUES('Lamont','MI','49430','Ottawa');
INSERT INTO zipcode VALUES('Ludington','MI','49431','Mason');
INSERT INTO zipcode VALUES('Macatawa','MI','49434','Ottawa');
INSERT INTO zipcode VALUES('Marne','MI','49435','Ottawa');
INSERT INTO zipcode VALUES('Mears','MI','49436','Oceana');
INSERT INTO zipcode VALUES('Montague','MI','49437','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49440','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49441','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49442','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49443','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49444','Muskegon');
INSERT INTO zipcode VALUES('Muskegon','MI','49445','Muskegon');
INSERT INTO zipcode VALUES('New Era','MI','49446','Oceana');
INSERT INTO zipcode VALUES('Nunica','MI','49448','Ottawa');
INSERT INTO zipcode VALUES('Pentwater','MI','49449','Oceana');
INSERT INTO zipcode VALUES('Pullman','MI','49450','Allegan');
INSERT INTO zipcode VALUES('Ravenna','MI','49451','Muskegon');
INSERT INTO zipcode VALUES('Rothbury','MI','49452','Oceana');
INSERT INTO zipcode VALUES('Saugatuck','MI','49453','Allegan');
INSERT INTO zipcode VALUES('Scottville','MI','49454','Mason');
INSERT INTO zipcode VALUES('Shelby','MI','49455','Oceana');
INSERT INTO zipcode VALUES('Spring Lake','MI','49456','Ottawa');
INSERT INTO zipcode VALUES('Twin Lake','MI','49457','Muskegon');
INSERT INTO zipcode VALUES('Walhalla','MI','49458','Mason');
INSERT INTO zipcode VALUES('Walkerville','MI','49459','Oceana');
INSERT INTO zipcode VALUES('West Olive','MI','49460','Ottawa');
INSERT INTO zipcode VALUES('Whitehall','MI','49461','Muskegon');
INSERT INTO zipcode VALUES('Wabaningo','MI','49463','Muskegon');
INSERT INTO zipcode VALUES('Zeeland','MI','49464','Ottawa');
INSERT INTO zipcode VALUES('Grandville','MI','49468','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49501','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49502','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49503','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49504','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49505','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49506','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49507','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49508','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49509','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49510','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49512','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49514','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49515','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49516','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49518','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49523','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49525','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49530','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49544','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49546','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49548','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49550','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49555','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49560','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49588','Kent');
INSERT INTO zipcode VALUES('Grand Rapids','MI','49599','Kent');
INSERT INTO zipcode VALUES('Cadillac','MI','49601','Wexford');
INSERT INTO zipcode VALUES('Acme','MI','49610','Grand Traverse');
INSERT INTO zipcode VALUES('Alba','MI','49611','Antrim');
INSERT INTO zipcode VALUES('Alden','MI','49612','Antrim');
INSERT INTO zipcode VALUES('Arcadia','MI','49613','Manistee');
INSERT INTO zipcode VALUES('Bear Lake','MI','49614','Manistee');
INSERT INTO zipcode VALUES('Bellaire','MI','49615','Antrim');
INSERT INTO zipcode VALUES('Benzonia','MI','49616','Benzie');
INSERT INTO zipcode VALUES('Beulah','MI','49617','Benzie');
INSERT INTO zipcode VALUES('Boon','MI','49618','Wexford');
INSERT INTO zipcode VALUES('Brethren','MI','49619','Manistee');
INSERT INTO zipcode VALUES('Buckley','MI','49620','Wexford');
INSERT INTO zipcode VALUES('Cedar','MI','49621','Leelanau');
INSERT INTO zipcode VALUES('Central Lake','MI','49622','Antrim');
INSERT INTO zipcode VALUES('Chase','MI','49623','Lake');
INSERT INTO zipcode VALUES('Copemish','MI','49625','Manistee');
INSERT INTO zipcode VALUES('Eastlake','MI','49626','Manistee');
INSERT INTO zipcode VALUES('Eastport','MI','49627','Antrim');
INSERT INTO zipcode VALUES('Elberta','MI','49628','Benzie');
INSERT INTO zipcode VALUES('Elk Rapids','MI','49629','Antrim');
INSERT INTO zipcode VALUES('Empire','MI','49630','Leelanau');
INSERT INTO zipcode VALUES('Evart','MI','49631','Osceola');
INSERT INTO zipcode VALUES('Falmouth','MI','49632','Missaukee');
INSERT INTO zipcode VALUES('Fife Lake','MI','49633','Kalkaska');
INSERT INTO zipcode VALUES('Filer City','MI','49634','Manistee');
INSERT INTO zipcode VALUES('Frankfort','MI','49635','Benzie');
INSERT INTO zipcode VALUES('Glen Arbor','MI','49636','Leelanau');
INSERT INTO zipcode VALUES('Grawn','MI','49637','Grand Traverse');
INSERT INTO zipcode VALUES('Harrietta','MI','49638','Wexford');
INSERT INTO zipcode VALUES('Hersey','MI','49639','Osceola');
INSERT INTO zipcode VALUES('Honor','MI','49640','Benzie');
INSERT INTO zipcode VALUES('Idlewild','MI','49642','Lake');
INSERT INTO zipcode VALUES('Interlochen','MI','49643','Grand Traverse');
INSERT INTO zipcode VALUES('Irons','MI','49644','Lake');
INSERT INTO zipcode VALUES('Kaleva','MI','49645','Manistee');
INSERT INTO zipcode VALUES('Kalkaska','MI','49646','Kalkaska');
INSERT INTO zipcode VALUES('Kewadin','MI','49648','Antrim');
INSERT INTO zipcode VALUES('Kingsley','MI','49649','Grand Traverse');
INSERT INTO zipcode VALUES('Lake Ann','MI','49650','Benzie');
INSERT INTO zipcode VALUES('Lake City','MI','49651','Missaukee');
INSERT INTO zipcode VALUES('Lake Leelanau','MI','49653','Leelanau');
INSERT INTO zipcode VALUES('Leland','MI','49654','Leelanau');
INSERT INTO zipcode VALUES('Leroy','MI','49655','Osceola');
INSERT INTO zipcode VALUES('Luther','MI','49656','Lake');
INSERT INTO zipcode VALUES('Mc Bain','MI','49657','Missaukee');
INSERT INTO zipcode VALUES('Mancelona','MI','49659','Antrim');
INSERT INTO zipcode VALUES('Manistee','MI','49660','Manistee');
INSERT INTO zipcode VALUES('Manton','MI','49663','Wexford');
INSERT INTO zipcode VALUES('Maple City','MI','49664','Leelanau');
INSERT INTO zipcode VALUES('Marion','MI','49665','Osceola');
INSERT INTO zipcode VALUES('Mayfield','MI','49666','Grand Traverse');
INSERT INTO zipcode VALUES('Merritt','MI','49667','Missaukee');
INSERT INTO zipcode VALUES('Mesick','MI','49668','Wexford');
INSERT INTO zipcode VALUES('Northport','MI','49670','Leelanau');
INSERT INTO zipcode VALUES('Old Mission','MI','49673','Grand Traverse');
INSERT INTO zipcode VALUES('Omena','MI','49674','Leelanau');
INSERT INTO zipcode VALUES('Onekama','MI','49675','Manistee');
INSERT INTO zipcode VALUES('Rapid City','MI','49676','Kalkaska');
INSERT INTO zipcode VALUES('Reed City','MI','49677','Osceola');
INSERT INTO zipcode VALUES('Sears','MI','49679','Osceola');
INSERT INTO zipcode VALUES('South Boardman','MI','49680','Kalkaska');
INSERT INTO zipcode VALUES('Suttons Bay','MI','49682','Leelanau');
INSERT INTO zipcode VALUES('Thompsonville','MI','49683','Benzie');
INSERT INTO zipcode VALUES('Traverse City','MI','49684','Grand Traverse');
INSERT INTO zipcode VALUES('Traverse City','MI','49685','Grand Traverse');
INSERT INTO zipcode VALUES('Traverse City','MI','49686','Grand Traverse');
INSERT INTO zipcode VALUES('Tustin','MI','49688','Osceola');
INSERT INTO zipcode VALUES('Wellston','MI','49689','Manistee');
INSERT INTO zipcode VALUES('Williamsburg','MI','49690','Grand Traverse');
INSERT INTO zipcode VALUES('Traverse City','MI','49696','Grand Traverse');
INSERT INTO zipcode VALUES('Mackinaw City','MI','49701','Cheboygan');
INSERT INTO zipcode VALUES('Afton','MI','49705','Cheboygan');
INSERT INTO zipcode VALUES('Alanson','MI','49706','Emmet');
INSERT INTO zipcode VALUES('Alpena','MI','49707','Alpena');
INSERT INTO zipcode VALUES('Atlanta','MI','49709','Montmorency');
INSERT INTO zipcode VALUES('Barbeau','MI','49710','Chippewa');
INSERT INTO zipcode VALUES('Bay Shore','MI','49711','Charlevoix');
INSERT INTO zipcode VALUES('Boyne City','MI','49712','Charlevoix');
INSERT INTO zipcode VALUES('Boyne Falls','MI','49713','Charlevoix');
INSERT INTO zipcode VALUES('Brimley','MI','49715','Chippewa');
INSERT INTO zipcode VALUES('Brutus','MI','49716','Emmet');
INSERT INTO zipcode VALUES('Burt Lake','MI','49717','Cheboygan');
INSERT INTO zipcode VALUES('Carp Lake','MI','49718','Emmet');
INSERT INTO zipcode VALUES('Cedarville','MI','49719','Mackinac');
INSERT INTO zipcode VALUES('Charlevoix','MI','49720','Charlevoix');
INSERT INTO zipcode VALUES('Cheboygan','MI','49721','Cheboygan');
INSERT INTO zipcode VALUES('Conway','MI','49722','Emmet');
INSERT INTO zipcode VALUES('Cross Village','MI','49723','Emmet');
INSERT INTO zipcode VALUES('Dafter','MI','49724','Chippewa');
INSERT INTO zipcode VALUES('De Tour','MI','49725','Michigan Chippewa');
INSERT INTO zipcode VALUES('Drummond Island','MI','49726','Chippewa');
INSERT INTO zipcode VALUES('East Jordan','MI','49727','Charlevoix');
INSERT INTO zipcode VALUES('Eckerman','MI','49728','Chippewa');
INSERT INTO zipcode VALUES('Ellsworth','MI','49729','Antrim');
INSERT INTO zipcode VALUES('Elmira','MI','49730','Otsego');
INSERT INTO zipcode VALUES('Frederic','MI','49733','Crawford');
INSERT INTO zipcode VALUES('Gaylord','MI','49734','Otsego');
INSERT INTO zipcode VALUES('Gaylord','MI','49735','Otsego');
INSERT INTO zipcode VALUES('Goetzville','MI','49736','Chippewa');
INSERT INTO zipcode VALUES('Good Hart','MI','49737','Emmet');
INSERT INTO zipcode VALUES('Grayling','MI','49738','Crawford');
INSERT INTO zipcode VALUES('Grayling','MI','49739','Crawford');
INSERT INTO zipcode VALUES('Harbor Springs','MI','49740','Emmet');
INSERT INTO zipcode VALUES('Hawks','MI','49743','Presque Isle');
INSERT INTO zipcode VALUES('Herron','MI','49744','Alpena');
INSERT INTO zipcode VALUES('Hessel','MI','49745','Mackinac');
INSERT INTO zipcode VALUES('Hillman','MI','49746','Montmorency');
INSERT INTO zipcode VALUES('Hubbard Lake','MI','49747','Alpena');
INSERT INTO zipcode VALUES('Hulbert','MI','49748','Chippewa');
INSERT INTO zipcode VALUES('Indian River','MI','49749','Cheboygan');
INSERT INTO zipcode VALUES('Johannesburg','MI','49751','Otsego');
INSERT INTO zipcode VALUES('Kinross','MI','49752','Chippewa');
INSERT INTO zipcode VALUES('Lachine','MI','49753','Alpena');
INSERT INTO zipcode VALUES('Levering','MI','49755','Emmet');
INSERT INTO zipcode VALUES('Lewiston','MI','49756','Montmorency');
INSERT INTO zipcode VALUES('Mackinac Island','MI','49757','Mackinac');
INSERT INTO zipcode VALUES('Millersburg','MI','49759','Presque Isle');
INSERT INTO zipcode VALUES('Moran','MI','49760','Mackinac');
INSERT INTO zipcode VALUES('Mullett Lake','MI','49761','Cheboygan');
INSERT INTO zipcode VALUES('Naubinway','MI','49762','Mackinac');
INSERT INTO zipcode VALUES('Oden','MI','49764','Emmet');
INSERT INTO zipcode VALUES('Onaway','MI','49765','Presque Isle');
INSERT INTO zipcode VALUES('Ossineke','MI','49766','Alpena');
INSERT INTO zipcode VALUES('Paradise','MI','49768','Chippewa');
INSERT INTO zipcode VALUES('Pellston','MI','49769','Emmet');
INSERT INTO zipcode VALUES('Petoskey','MI','49770','Emmet');
INSERT INTO zipcode VALUES('Pickford','MI','49774','Chippewa');
INSERT INTO zipcode VALUES('Pointe Aux','MI','49775','Michigan Mackinac');
INSERT INTO zipcode VALUES('Posen','MI','49776','Presque Isle');
INSERT INTO zipcode VALUES('Presque Isle','MI','49777','Presque Isle');
INSERT INTO zipcode VALUES('Brimley','MI','49778','Chippewa');
INSERT INTO zipcode VALUES('Rogers City','MI','49779','Presque Isle');
INSERT INTO zipcode VALUES('Rudyard','MI','49780','Chippewa');
INSERT INTO zipcode VALUES('Saint Ignace','MI','49781','Mackinac');
INSERT INTO zipcode VALUES('Beaver Island','MI','49782','Charlevoix');
INSERT INTO zipcode VALUES('Sault Sainte','MI','49783','Michigan Chippewa');
INSERT INTO zipcode VALUES('Kincheloe','MI','49784','Chippewa');
INSERT INTO zipcode VALUES('Kincheloe','MI','49785','Chippewa');
INSERT INTO zipcode VALUES('Kincheloe','MI','49786','Chippewa');
INSERT INTO zipcode VALUES('Kincheloe','MI','49788','Chippewa');
INSERT INTO zipcode VALUES('Strongs','MI','49790','Chippewa');
INSERT INTO zipcode VALUES('Topinabee','MI','49791','Cheboygan');
INSERT INTO zipcode VALUES('Tower','MI','49792','Cheboygan');
INSERT INTO zipcode VALUES('Trout Lake','MI','49793','Chippewa');
INSERT INTO zipcode VALUES('Vanderbilt','MI','49795','Otsego');
INSERT INTO zipcode VALUES('Walloon Lake','MI','49796','Charlevoix');
INSERT INTO zipcode VALUES('Waters','MI','49797','Otsego');
INSERT INTO zipcode VALUES('Wolverine','MI','49799','Cheboygan');
INSERT INTO zipcode VALUES('Iron Mountain','MI','49801','Dickinson');
INSERT INTO zipcode VALUES('Kingsford','MI','49802','Dickinson');
INSERT INTO zipcode VALUES('Allouez','MI','49805','Keweenaw');
INSERT INTO zipcode VALUES('Au Train','MI','49806','Alger');
INSERT INTO zipcode VALUES('Bark River','MI','49807','Delta');
INSERT INTO zipcode VALUES('Big Bay','MI','49808','Marquette');
INSERT INTO zipcode VALUES('Carney','MI','49812','Menominee');
INSERT INTO zipcode VALUES('-','MI','49813','-');
INSERT INTO zipcode VALUES('Champion','MI','49814','Marquette');
INSERT INTO zipcode VALUES('Channing','MI','49815','Dickinson');
INSERT INTO zipcode VALUES('Chatham','MI','49816','Alger');
INSERT INTO zipcode VALUES('Cooks','MI','49817','Schoolcraft');
INSERT INTO zipcode VALUES('Cornell','MI','49818','Delta');
INSERT INTO zipcode VALUES('Arnold','MI','49819','Marquette');
INSERT INTO zipcode VALUES('Curtis','MI','49820','Mackinac');
INSERT INTO zipcode VALUES('Daggett','MI','49821','Menominee');
INSERT INTO zipcode VALUES('Deerton','MI','49822','Alger');
INSERT INTO zipcode VALUES('Eben Junction','MI','49825','Alger');
INSERT INTO zipcode VALUES('Rumely','MI','49826','Alger');
INSERT INTO zipcode VALUES('Engadine','MI','49827','Mackinac');
INSERT INTO zipcode VALUES('Escanaba','MI','49829','Delta');
INSERT INTO zipcode VALUES('Felch','MI','49831','Dickinson');
INSERT INTO zipcode VALUES('Little Lake','MI','49833','Marquette');
INSERT INTO zipcode VALUES('Foster City','MI','49834','Dickinson');
INSERT INTO zipcode VALUES('Garden','MI','49835','Delta');
INSERT INTO zipcode VALUES('Germfask','MI','49836','Schoolcraft');
INSERT INTO zipcode VALUES('Gladstone','MI','49837','Delta');
INSERT INTO zipcode VALUES('Gould City','MI','49838','Mackinac');
INSERT INTO zipcode VALUES('Grand Marais','MI','49839','Alger');
INSERT INTO zipcode VALUES('Gulliver','MI','49840','Schoolcraft');
INSERT INTO zipcode VALUES('Gwinn','MI','49841','Marquette');
INSERT INTO zipcode VALUES('Harris','MI','49845','Menominee');
INSERT INTO zipcode VALUES('Hermansville','MI','49847','Menominee');
INSERT INTO zipcode VALUES('Ingalls','MI','49848','Menominee');
INSERT INTO zipcode VALUES('Ishpeming','MI','49849','Marquette');
INSERT INTO zipcode VALUES('Loretto','MI','49852','Dickinson');
INSERT INTO zipcode VALUES('Mc Millan','MI','49853','Luce');
INSERT INTO zipcode VALUES('Manistique','MI','49854','Schoolcraft');
INSERT INTO zipcode VALUES('Marquette','MI','49855','Marquette');
INSERT INTO zipcode VALUES('Menominee','MI','49858','Menominee');
INSERT INTO zipcode VALUES('Michigamme','MI','49861','Marquette');
INSERT INTO zipcode VALUES('Munising','MI','49862','Alger');
INSERT INTO zipcode VALUES('Nadeau','MI','49863','Menominee');
INSERT INTO zipcode VALUES('Nahma','MI','49864','Delta');
INSERT INTO zipcode VALUES('National Mine','MI','49865','Marquette');
INSERT INTO zipcode VALUES('Negaunee','MI','49866','Marquette');
INSERT INTO zipcode VALUES('Newberry','MI','49868','Luce');
INSERT INTO zipcode VALUES('Norway','MI','49870','Dickinson');
INSERT INTO zipcode VALUES('Palmer','MI','49871','Marquette');
INSERT INTO zipcode VALUES('Perkins','MI','49872','Delta');
INSERT INTO zipcode VALUES('Perronville','MI','49873','Menominee');
INSERT INTO zipcode VALUES('Powers','MI','49874','Menominee');
INSERT INTO zipcode VALUES('Quinnesec','MI','49876','Dickinson');
INSERT INTO zipcode VALUES('Ralph','MI','49877','Dickinson');
INSERT INTO zipcode VALUES('Rapid River','MI','49878','Delta');
INSERT INTO zipcode VALUES('Republic','MI','49879','Marquette');
INSERT INTO zipcode VALUES('Rock','MI','49880','Delta');
INSERT INTO zipcode VALUES('Sagola','MI','49881','Dickinson');
INSERT INTO zipcode VALUES('Seney','MI','49883','Schoolcraft');
INSERT INTO zipcode VALUES('Shingleton','MI','49884','Alger');
INSERT INTO zipcode VALUES('Skandia','MI','49885','Marquette');
INSERT INTO zipcode VALUES('Spalding','MI','49886','Menominee');
INSERT INTO zipcode VALUES('Stephenson','MI','49887','Menominee');
INSERT INTO zipcode VALUES('Trenary','MI','49891','Alger');
INSERT INTO zipcode VALUES('Vulcan','MI','49892','Dickinson');
INSERT INTO zipcode VALUES('Wallace','MI','49893','Menominee');
INSERT INTO zipcode VALUES('Wells','MI','49894','Delta');
INSERT INTO zipcode VALUES('Wetmore','MI','49895','Alger');
INSERT INTO zipcode VALUES('Wilson','MI','49896','Menominee');
INSERT INTO zipcode VALUES('Ahmeek','MI','49901','Keweenaw');
INSERT INTO zipcode VALUES('Alpha','MI','49902','Iron');
INSERT INTO zipcode VALUES('Amasa','MI','49903','Iron');
INSERT INTO zipcode VALUES('Atlantic Mine','MI','49905','Houghton');
INSERT INTO zipcode VALUES('Baraga','MI','49908','Baraga');
INSERT INTO zipcode VALUES('Bergland','MI','49910','Ontonagon');
INSERT INTO zipcode VALUES('Bessemer','MI','49911','Gogebic');
INSERT INTO zipcode VALUES('Bruce Crossing','MI','49912','Ontonagon');
INSERT INTO zipcode VALUES('Calumet','MI','49913','Houghton');
INSERT INTO zipcode VALUES('Caspian','MI','49915','Iron');
INSERT INTO zipcode VALUES('Chassell','MI','49916','Houghton');
INSERT INTO zipcode VALUES('Copper City','MI','49917','Houghton');
INSERT INTO zipcode VALUES('Copper Harbor','MI','49918','Keweenaw');
INSERT INTO zipcode VALUES('Covington','MI','49919','Baraga');
INSERT INTO zipcode VALUES('Crystal Falls','MI','49920','Iron');
INSERT INTO zipcode VALUES('Dodgeville','MI','49921','Houghton');
INSERT INTO zipcode VALUES('Dollar Bay','MI','49922','Houghton');
INSERT INTO zipcode VALUES('Ewen','MI','49925','Ontonagon');
INSERT INTO zipcode VALUES('Gaastra','MI','49927','Iron');
INSERT INTO zipcode VALUES('Greenland','MI','49929','Ontonagon');
INSERT INTO zipcode VALUES('Hancock','MI','49930','Houghton');
INSERT INTO zipcode VALUES('Houghton','MI','49931','Houghton');
INSERT INTO zipcode VALUES('Hubbell','MI','49934','Houghton');
INSERT INTO zipcode VALUES('Iron River','MI','49935','Iron');
INSERT INTO zipcode VALUES('Ironwood','MI','49938','Gogebic');
INSERT INTO zipcode VALUES('Kearsarge','MI','49942','Houghton');
INSERT INTO zipcode VALUES('Lake Linden','MI','49945','Houghton');
INSERT INTO zipcode VALUES('Lanse','MI','49946','Baraga');
INSERT INTO zipcode VALUES('Marenisco','MI','49947','Gogebic');
INSERT INTO zipcode VALUES('Mass City','MI','49948','Ontonagon');
INSERT INTO zipcode VALUES('Mohawk','MI','49950','Keweenaw');
INSERT INTO zipcode VALUES('Nisula','MI','49952','Houghton');
INSERT INTO zipcode VALUES('Ontonagon','MI','49953','Ontonagon');
INSERT INTO zipcode VALUES('Painesdale','MI','49955','Houghton');
INSERT INTO zipcode VALUES('Pelkie','MI','49958','Houghton');
INSERT INTO zipcode VALUES('Ramsay','MI','49959','Gogebic');
INSERT INTO zipcode VALUES('Rockland','MI','49960','Ontonagon');
INSERT INTO zipcode VALUES('Sidnaw','MI','49961','Houghton');
INSERT INTO zipcode VALUES('Skanee','MI','49962','Baraga');
INSERT INTO zipcode VALUES('South Range','MI','49963','Houghton');
INSERT INTO zipcode VALUES('Stambaugh','MI','49964','Iron');
INSERT INTO zipcode VALUES('Toivola','MI','49965','Houghton');
INSERT INTO zipcode VALUES('Trout Creek','MI','49967','Ontonagon');
INSERT INTO zipcode VALUES('Wakefield','MI','49968','Gogebic');
INSERT INTO zipcode VALUES('Watersmeet','MI','49969','Gogebic');
INSERT INTO zipcode VALUES('Watton','MI','49970','Baraga');
INSERT INTO zipcode VALUES('White Pine','MI','49971','Ontonagon');
